from tkinter import *
root=Tk()
frame=Frame(root,width=600,height=600)
frame.pack(expand=True, fill=BOTH) #.grid(row=0,column=0)
canvas=Canvas(frame,bg='#FFFFFF',width=600,height=600,scrollregion=(0,0,500,900))
#hbar=Scrollbar(frame,orient=HORIZONTAL)
#hbar.pack(side=BOTTOM,fill=X)
#hbar.config(command=canvas.xview)
vbar=Scrollbar(frame,orient=VERTICAL)
vbar.pack(side=RIGHT,fill=Y)
vbar.config(command=canvas.yview)
canvas.config(width=600,height=600, background="white")
canvas.config(yscrollcommand=vbar.set)
canvas.pack(side=LEFT,expand=True,fill=BOTH)
canvas.create_text(100,10, text="Hello World!")
canvas.create_text(100,900, text="Hello World!")
root.mainloop()
